import { StyleSheet, Platform, Dimensions, StatusBar } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallDevice = width < 375;

// Enhanced color palette with dark mode support
export const colors = {
  light: {
    primary: '#4361EE',
    primaryDark: '#3A56D4',
    primaryLight: '#EEF1FF',
    secondary: '#F72585',
    secondaryLight: '#FEEBF5',
    accent: '#7209B7',
    background: '#F8F9FE',
    surfaceElevated: '#FFFFFF',
    surface: '#F0F2FA',
    text: '#1F2937',
    textSecondary: '#6B7280',
    textTertiary: '#9CA3AF',
    border: '#E5E7EB',
    success: '#10B981',
    warning: '#FBBF24',
    danger: '#EF4444',
    shadow: 'rgba(0, 0, 0, 0.08)',
    shadowStrong: 'rgba(0, 0, 0, 0.12)',
    shimmer: '#F0F0F0',
  },
  dark: {
    primary: '#4361EE',
    primaryDark: '#3A56D4',
    primaryLight: '#1E293B',
    secondary: '#F72585',
    secondaryLight: '#31223B',
    accent: '#7209B7',
    background: '#0F172A',
    surfaceElevated: '#1E293B',
    surface: '#1E293B',
    text: '#F9FAFB',
    textSecondary: '#9CA3AF',
    textTertiary: '#6B7280',
    border: '#374151',
    success: '#10B981',
    warning: '#FBBF24',
    danger: '#EF4444',
    shadow: 'rgba(0, 0, 0, 0.3)',
    shadowStrong: 'rgba(0, 0, 0, 0.5)',
    shimmer: '#2D3748',
  }
};

// Common styles and values
const fontFamily = {
  regular: 'System',
  medium: 'System',
  semiBold: 'System',
  bold: 'System',
};

// Shadow styles for different elevations
const shadows = {
  small: {
    shadowColor: colors.light.shadowStrong,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: colors.light.shadowStrong,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: colors.light.shadowStrong,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 8,
  },
};

export const createStyles = (theme: 'light' | 'dark') => {
  const currentColors = colors[theme];
  
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: currentColors.background,
      paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight || 0,
    },
    contentContainer: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 24,
    },
    glassContainer: {
      width: width * 0.92,
      maxWidth: 500,
      padding: 24,
      backgroundColor: currentColors.surfaceElevated,
      borderRadius: 24,
      shadowColor: currentColors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 8,
      marginTop: 16,
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    searchButton: {
      backgroundColor: currentColors.primary,
      padding: isSmallDevice ? 14 : 16,
      borderRadius: 16,
      alignItems: 'center',
      marginTop: 24,
      shadowColor: currentColors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    searchButtonText: {
      color: '#FFFFFF',
      fontFamily: fontFamily.bold,
      fontSize: isSmallDevice ? 15 : 16,
      letterSpacing: 0.5,
    },
    searchButtonDisabled: {
      backgroundColor: currentColors.textTertiary,
      shadowOpacity: 0.1,
    },
    titleContainer: {
      alignItems: 'center',
      width: '100%',
      marginBottom: isSmallDevice ? 20 : 30,
      paddingTop: 10,
    },
    appTitle: {
      fontSize: isSmallDevice ? 32 : 38,
      fontFamily: fontFamily.bold,
      color: currentColors.primary,
      letterSpacing: 1,
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
      marginBottom: 8,
    },
    title: {
      fontSize: isSmallDevice ? 14 : 16,
      color: currentColors.textSecondary,
      marginBottom: 8,
      fontStyle: 'italic',
      letterSpacing: 0.5,
    },
    titleText: {
      fontSize: isSmallDevice ? 24 : 28,
      fontFamily: fontFamily.semiBold,
      color: currentColors.primary,
      marginBottom: 24,
    },
    inputContainer: {
      gap: 20,
    },
    searchResults: {
      backgroundColor: currentColors.surfaceElevated,
      borderRadius: 16,
      marginTop: -12,
      marginBottom: 10,
      paddingVertical: 8,
      maxHeight: 200,
      shadowColor: currentColors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
      zIndex: 2,
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    searchResultItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: currentColors.border,
    },
    searchResultText: {
      fontSize: 14,
      color: currentColors.text,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: isSmallDevice ? 14 : 16,
      borderRadius: 16,
      backgroundColor: currentColors.surfaceElevated,
      borderWidth: 1,
      borderColor: currentColors.border,
      shadowColor: currentColors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    inputWrapperFocused: {
      borderColor: currentColors.primary,
      borderWidth: 2,
    },
    input: {
      flex: 1,
      fontSize: isSmallDevice ? 14 : 16,
      color: currentColors.text,
      fontFamily: fontFamily.regular,
    },
    clearButton: {
      fontSize: 20,
      color: currentColors.textSecondary,
      padding: 6,
    },
    locationButton: {
      fontSize: 20,
      padding: 6,
      color: currentColors.primary,
    },
    busRoutesContainer: {
      flex: 1,
      width: '100%',
      backgroundColor: currentColors.background,
      borderRadius: 24,
      overflow: 'hidden',
      shadowColor: currentColors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 8,
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    busRoutesHeader: {
      padding: 16,
      backgroundColor: currentColors.surfaceElevated,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: currentColors.border,
    },
    busRoutesTitle: {
      fontSize: isSmallDevice ? 18 : 20,
      fontFamily: fontFamily.semiBold,
      color: currentColors.text,
      marginLeft: 16,
    },
    busRoutesList: {
      padding: 16,
    },
    backButton: {
      padding: 8,
      backgroundColor: currentColors.primaryLight,
      borderRadius: 12,
    },
    backButtonText: {
      fontSize: 16,
      color: currentColors.primary,
      fontFamily: fontFamily.medium,
    },
    busRouteContainer: {
      backgroundColor: currentColors.surfaceElevated,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      shadowColor: currentColors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: theme === 'dark' ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    busHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    busNumber: {
      fontSize: isSmallDevice ? 16 : 18,
      marginTop: 4,
      marginBottom: 4,
      fontFamily: fontFamily.bold,
      color: currentColors.primary,
      backgroundColor: currentColors.primaryLight,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      overflow: 'hidden',
    },
    timeContainer: {
      marginTop: 4,
      marginBottom: 8,
      backgroundColor: currentColors.primaryLight,
      padding: 12,
      borderRadius: 12,
    },
    timeText: {
      fontSize: 14,
      color: theme === 'dark' ? currentColors.textSecondary : currentColors.text,
      fontFamily: fontFamily.regular,
    },
    routeInfo: {
      marginTop: 12,
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: currentColors.border,
      borderRadius: 16,
      backgroundColor: currentColors.surface,
    },
    routeText: {
      fontSize: 14,
      color: currentColors.textSecondary,
      marginBottom: 6,
      lineHeight: 20,
      fontFamily: fontFamily.regular,
    },
    statusText: {
      fontSize: 14,
      fontFamily: fontFamily.semiBold,
    },
    noRoutesText: {
      fontSize: 16,
      color: currentColors.textSecondary,
      textAlign: 'center',
      marginTop: 40,
      marginBottom: 16,
      fontFamily: fontFamily.medium,
    },
    locationIcon: {
      marginRight: 8,
      color: currentColors.primary,
    },
    divider: {
      height: 1,
      backgroundColor: currentColors.border,
      width: '100%',
      marginVertical: 8,
    },
    logoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logo: {
      width: 40,
      height: 40,
      marginRight: 10,
    },
    adContainer: {
      backgroundColor: theme === 'dark' ? '#2D2A1C' : "beige",
      padding: 16,
      margin: 16,
      borderRadius: 8,
      alignItems: "center",
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    adTitle: {
      fontSize: 18,
      fontFamily: fontFamily.bold,
      color: currentColors.text,
      marginBottom: 8,
    },
    adImage: {
      width: "100%",
      height: 150,
      borderRadius: 8,
      marginBottom: 8,
    },
    adText: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: 8,
      color: currentColors.text,
      fontFamily: fontFamily.regular,
    },
    adCTA: {
      fontSize: 16,
      fontFamily: fontFamily.bold,
      color: theme === 'dark' ? "#ff6b6b" : "#d32f2f",
    },
    // New enhanced styles
    gradientBorder: {
      position: 'absolute',
      top: -2,
      left: -2,
      right: -2,
      bottom: -2,
      borderRadius: 22,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    badge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 99,
      backgroundColor: currentColors.secondaryLight,
      alignSelf: 'flex-start',
    },
    badgeText: {
      color: currentColors.secondary,
      fontSize: 12,
      fontFamily: fontFamily.medium,
    },
    crowdIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
      borderRadius: 8,
      marginTop: 8,
    },
    crowdIndicatorLow: {
      backgroundColor: theme === 'dark' ? 'rgba(16, 185, 129, 0.2)' : 'rgba(16, 185, 129, 0.1)',
    },
    crowdIndicatorMedium: {
      backgroundColor: theme === 'dark' ? 'rgba(251, 191, 36, 0.2)' : 'rgba(251, 191, 36, 0.1)',
    },
    crowdIndicatorHigh: {
      backgroundColor: theme === 'dark' ? 'rgba(239, 68, 68, 0.2)' : 'rgba(239, 68, 68, 0.1)',
    },
    shimmerContainer: {
      backgroundColor: currentColors.surfaceElevated,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      ...shadows.medium,
    },
    shimmerBox: {
      height: 20,
      backgroundColor: currentColors.shimmer,
      borderRadius: 4,
      marginBottom: 8,
    },
    floatingButton: {
      position: 'absolute',
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: currentColors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.medium,
    },
    themeToggle: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight ? StatusBar.currentHeight + 10 : 10,
      right: 20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: currentColors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.small,
      zIndex: 999,
    },
    buttonWithIcon: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    sectionTitle: {
      fontSize: 16,
      fontFamily: fontFamily.semiBold,
      color: currentColors.text,
      marginBottom: 4,
    },
    pill: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 99,
      backgroundColor: currentColors.primaryLight,
      marginRight: 8,
      marginBottom: 8,
    },
    pillText: {
      fontSize: 14,
      color: currentColors.primary,
      fontFamily: fontFamily.medium,
    },
    card: {
      backgroundColor: currentColors.surfaceElevated,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      ...shadows.medium,
      borderWidth: theme === 'dark' ? 1 : 0,
      borderColor: currentColors.border,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    spaceBetween: {
      justifyContent: 'space-between',
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: currentColors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarGradient: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontFamily: fontFamily.bold,
    },
    progressBar: {
      height: 8,
      borderRadius: 4,
      backgroundColor: currentColors.border,
      marginVertical: 8,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
    },
    progressFillLow: {
      backgroundColor: currentColors.success,
    },
    progressFillMedium: {
      backgroundColor: currentColors.warning,
    },
    progressFillHigh: {
      backgroundColor: currentColors.danger,
    },
    // New enhanced styles
    routeLocations: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    locationIndicator: {
      width: 20,
      alignItems: 'center',
      marginRight: 12,
    },
    locationTexts: {
      flex: 1,
    },
    startDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: currentColors.primary,
    },
    endDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: currentColors.secondary,
    },
    routeLine: {
      width: 2,
      height: 24,
      backgroundColor: currentColors.border,
      marginVertical: 4,
      alignSelf: 'center',
    },
    startLocationText: {
      fontSize: 14,
      fontFamily: fontFamily.medium,
      color: currentColors.text,
      marginBottom: 16,
    },
    endLocationText: {
      fontSize: 14,
      fontFamily: fontFamily.medium,
      color: currentColors.text,
    },
    detailsButton: {
      backgroundColor: currentColors.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 12,
      ...shadows.small,
    },
    detailsButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontFamily: fontFamily.medium,
    },
    statusChip: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      marginBottom: 8,
    },
  });
};

// Export a default styles object with light theme
export const styles = createStyles('light');